### ISSUE TITLE
challenged words are not removed from the board

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#12]
Tried a test game where I was playing both sides via two local accounts.  I challenged the first word put down and the challenge was successful, but the word stayed on the board.  I didn't seem to be able to add anything onto the word nor put other letters over top of it.  Thanks.

**Comment by pkolano** [comment]
After more testing, it seems that the actual issue is that the board isn't being refreshed.  If I close the game and then rejoin the game, the board is correct with the challenged word removed, but remains on the board indefinitely with no play possible if you don't do this.

**Comment by cdot** [comment]
Thanks - I changed the board refresh code recently and haven't ironed out all the bugs yet!

**Comment by cdot** [comment]
I believe this should now be resolved.

**Comment by jlbribeiro** [comment]
@pkolano Just to add a bit more context: I believe the server was correctly handling the challenge/take back, but the UI would crash when applying it because of [this typo](https://github.com/cdot/Xanado/blob/7fe2f17281f2b1f01598b244c07399519606dbd9/js/browser/Ui.js#L1223) (I had the PR ready as well :P ). But @cdot just pushed a bunch of changes, seems to be fixed!
Thank you for your improvements, @cdot!
