### ISSUE TITLE
format of .game files

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#133]
So I had been working on and off on a perl script that parses the .game files and produces a bunch of advanced stats on various things (embedded in a simple html/cgi combo for those running their own server).  I had been basing it off of some game files I had downloaded from my server back in 2022.  I finally had some time to finish it, but then when I went to run it against the current full set of games, I saw that the .game format had been changed at some point from standard JSON to some kind of compressed JSON.

Is there any tool you already have or could provide that could translate this format back to standard JSON?  Or is it some standard JSON variant that might be supported elsewhere (e.g. in an existing linux command line tool, perl module, etc.)?  I was planning on sharing it with you once I got it all vetted since others might be interested in such a thing.  Anyway, please let me know.  Thanks!

**Comment by cdot** [comment]
The files are in a format called ["CBOR"](https://en.wikipedia.org/wiki/CBOR). There is no direct equivalent JSON, because the game structure is circular - which CBOR supports, but JSON does not. However you can generate a JSON-like dump (where circular references are replaced with [Circular]) as follows:
```
import { promises as Fs } from "fs";
import { inspect } from 'util';
import { CBOR } from "./src/game/CBOR.js";
import { Game } from "./src/game/Game.js";

const GAME_FILE = "games/f499bfc2f7930324.game";
Fs.readFile(GAME_FILE)
.then(data => CBOR.decode(data, Game.CLASSES))
.then(game => console.log(inspect(game)));
```
Save this code to the root of the distribution, modify it to read your specific game file.

Note that the .game file format is likely to change in the future; I try to maintain compatibility with old game files, but can't always guarantee it,  sorry.

**Comment by pkolano** [comment]
Thank you.  It kind of works, but most of the critical data is printed as [Array], [Object], [Tile], [Rack].  Is there any way to expand that stuff out?  I tried some perl and python CBOR modules, but they don't seem to like the game files and abort after the first few bytes.

**Comment by pkolano** [comment]
Nevermind, I figured it out by searching online.  If you make it:

> .then(game => console.log(inspect(game,{depth:null})));

It will expand everything out.  Thanks, this should work.
