### ISSUE TITLE
Letter distribution chart on the right

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#16]
Would be nice to have a letter distribution chart on the right.  Don't know if it could be used given your changes to the code, but there was a pull request to the hanshuebner version that did this at https://github.com/hanshuebner/html-scrabble/pull/77.  Thanks!

**Comment by cdot** [comment]
I looked at that PR but decided not to follow up on it because it uses so much screen real estate, and would give an unfair advantage to players on desktop and tablet devices versus those on mobiles (yeas, I have a couple of those!). However it would be easy enough to add, and could be useful for those learning to play at competition level where tracking the remaining letters in the bag becomes an issue. The PR as given would not work with the current code, but the principle would be simple enough to apply. I'd want it to be optionally enabled by the game creator, and optionally displayed under user settings control.

**Comment by cdot** [comment]
It's there in 2.1.2
