### ISSUE TITLE
Games stats should be average score and not total

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#26]
Right now, the leader board shows total score, but this doesn't mean much since the more games you play, the more you will score.  It should probably be an average score and then need to weight somehow.  For example, choose some default like 3 player and then scale the scores for 4+ and 2 player games using total tiles over number of players.  Or perhaps, if you keep track of tiles played, could do something like average points per word or average points per tile.  Anyway, just a thought.  Thanks.

**Comment by pkolano** [comment]
Would also be nice if it shows games played so number of wins can be put in context.

**Comment by pkolano** [comment]
Think another fun stat would be average value of tiles picked up so you could see who was "luckiest".  If you also had average points per tile scored mentioned above, you could then see who does more with less, etc.

**Comment by cdot** [comment]
The total for all games is shown because that's how we use it for tournament play. A tournament starts with an empty games database, then when all games are played the winner is the person with the highest total score. That helps iron out the essential randomness of tile picks.

Maybe showing the average and games played as well as the total is the way to go. I really like the idea of "luckiest" player, that could even be applied as a normalising factor in tournament play.
