### ISSUE TITLE
Game allowed player to challenge twice on the same turn

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#50]
On the latest, someone hit the challenge button, but it appeared to not do anything for a few seconds and they hit again and it challenged both the last word and the word two players before:

![doublechallenge](https://user-images.githubusercontent.com/20344426/176821479-fe2c9bdd-1494-4c88-9c66-e2eb9d13c76c.png)

**Comment by cdot** [comment]
Ouch - that sounds like network latency. The latest code was reworked to allow for an undo, primarily to aid debugging. I suspect that just bit. :-( If you have the game file that would be helpful, so I can see the turn timing.

**Comment by pkolano** [comment]
here it is:

[a21800dfb206973a.log](https://github.com/cdot/Xanado/files/9032051/a21800dfb206973a.log)

**Comment by cdot** [comment]
When you click a button, an event is queued in the UI. If the browser is busy for some reason and can't immediately handle the event, it is possible that a second click event could be queued before the UI is disabled to prevent a double challenge. Processing each of these events will result in a "challenge" command being sent to the server. Two challenge commands were received from Joe, at 03:42:26.870 and 03:42:26.952 respectively i.e. 82ms apart, strongly suggesting that this is what happened.

The server always assumes that an incoming challenge applies to the most recent play in the turn history that is not followed by a take-back or a successful challenge. The first challenge is won by Joe, so Paul's turn is skipped when looking back for the last play. The next earliest play in the turn history is John's play, which is valid so the challenge fails. Joe is marked as missing their turn due to the failed challenge, and the turn is passed to Mum.

Challenges should be marked with the challenged turn to eliminate this risk.

**Comment by cdot** [comment]
That should be OK now. I'm curious how the double challenge arose; was the client a non-mainstream browser (e.g. Safari)?
