### ISSUE TITLE
wrong letters reported at game end

### ISSUE THREAD

**Issue by pkolano** [cdot/Xanado#55]
On latest version, it says the wrong tiles are remaining at the end of the game.  Seems to do the scoring right even though it says the wrong thing.  Can see here the Z is already on the board, but it says it's remaining in John's hand (was actually Q and R):

![endtiles](https://user-images.githubusercontent.com/20344426/188063242-0c714dae-796c-48b6-a0b2-1faba0bfc7b2.png)

When you refresh, it fixes everything.

**Comment by cdot** [comment]
Any logs for me, please, Paul? Especially interested in any errors in the console on the client.

**Comment by pkolano** [comment]
I don't have a client log (not sure where I'd even get that), but here is the server log and game file:

[server.log](https://github.com/cdot/Xanado/files/9491457/server.log)
[975a818384fe75a4.log](https://github.com/cdot/Xanado/files/9491460/975a818384fe75a4.log)

**Comment by cdot** [comment]
Ah, stupid. I added code to anonymise the letters sent back to player's racks so that only the playing player sees the real new letters coming into their rack; other players see random letters. This is to prevent players reverse-engineering what is in other player's racks by watching the comms stream. This can be fixed by getting the server to report the final racks, as it is the only place that actually knows all the racks at the end of the game.

To get the client log, in the browser (e.g. Firefox) menu item "More tools" -> "Web Developer Tools" and click on "console". Copy-paste what you see there.

**Comment by cdot** [comment]
fixed in branch release/2.1.1
